const units = {
  recife: { name: 'Recife · Boa Viagem', description: 'Cozinha completa · Retirada em 15–20 min', short: 'Recife · Boa Viagem' },
  olinda: { name: 'Olinda · Centro', description: 'Cozinha reduzida · Retirada em 20–25 min', short: 'Olinda · Centro' },
  caruaru: { name: 'Caruaru · Maurício de Nassau', description: 'Cozinha completa · Retirada em 15–20 min', short: 'Caruaru · Maurício de Nassau' }
};
const products = [
  {id:'cuscuz-carne',name:'Cuscuz com carne de sol',category:'Cuscuz',description:'Cuscuz de milho, carne de sol desfiada e manteiga de garrafa.',price:2290,image:'images/cuscuz-carne.jpg',tag:'MAIS PEDIDO',stock:{recife:12,olinda:0,caruaru:9}},
  {id:'tapioca-coalho',name:'Tapioca de queijo coalho',category:'Tapiocas',description:'Queijo coalho douradinho, melaço de cana e um toque de orégano.',price:1750,image:'images/tapioca-queijo-coalho.jpg',tag:'FEITA NA HORA',stock:{recife:18,olinda:10,caruaru:14}},
  {id:'bolo-macaxeira',name:'Bolo de macaxeira',category:'Bolos',description:'Macio por dentro, douradinho por fora. Receita de família.',price:950,image:'images/bolo-macaxeira.jpg',stock:{recife:8,olinda:7,caruaru:10}},
  {id:'suco-umbu',name:'Suco de umbu',category:'Bebidas',description:'Fruta da estação, geladinha e com sabor da nossa terra.',price:850,image:'images/suco-umbu.jpg',stock:{recife:15,olinda:0,caruaru:12}},
  {id:'tapioca-banana',name:'Tapioca de banana e canela',category:'Tapiocas',description:'Banana madura, canela e um fio de melado.',price:1450,image:'images/tapioca-banana-canela.jpg',stock:{recife:12,olinda:9,caruaru:10}},
  {id:'cafe-coado',name:'Café coado na hora',category:'Bebidas',description:'Café regional passado na hora, do jeitinho de casa.',price:550,image:'images/cafe-coado.jpg',stock:{recife:30,olinda:28,caruaru:32}},
  {id:'pamonha-junina',name:'Pamonha assada de milho',category:'Sazonais',description:'Receita junina de milho verde, servida quentinha.',price:1100,image:'images/pamonha-assada.jpg',tag:'SAZONAL · JUNHO',seasonal:true,stock:{recife:0,olinda:0,caruaru:0}},
  {id:'cuscuz-veg',name:'Cuscuz de legumes',category:'Cuscuz',description:'Cuscuz amarelinho com legumes da estação e ervas frescas.',price:1890,image:'images/cuscuz-legumes.jpg',stock:{recife:8,olinda:0,caruaru:6}}
];
const categories = ['Tudo','Cuscuz','Tapiocas','Bolos','Bebidas','Sazonais'];
const state = {unit:'recife',channel:'web',category:'Tudo',search:'',cart:{},order:readOrder(),rewardApplied:false,points:120};
const $ = (selector, root=document) => root.querySelector(selector);
const money = cents => (cents/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const productById = id => products.find(product => product.id === id);

function readOrder(){try{return JSON.parse(localStorage.getItem('raizes-last-order')||'null')}catch{return null}}
function saveOrder(){if(state.order){const safe={code:state.order.code,unit:state.order.unit,items:state.order.items,total:state.order.total,discount:state.order.discount||0,status:state.order.status,createdAt:state.order.createdAt};try{localStorage.setItem('raizes-last-order',JSON.stringify(safe))}catch{showToast('Pedido disponível apenas nesta sessão; armazenamento local indisponível.')}$('#order-open').hidden=false}}
function stockFor(product){return product.stock[state.unit]||0}
function available(product){return stockFor(product)>0&&!product.seasonal}
function showToast(message){const toast=$('#toast');toast.textContent=message;toast.classList.add('visible');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('visible'),2700)}
function setDialog(id){const dialog=document.getElementById(id);if(dialog&&!dialog.open)dialog.showModal()}
function closeDialog(id){const dialog=document.getElementById(id);if(dialog?.open)dialog.close()}

function renderCategories(){const row=$('#category-row');row.innerHTML=categories.map(category=>`<button class="category-chip" type="button" aria-pressed="${state.category===category}" data-category="${category}">${category}</button>`).join('')}
function renderProducts(){const grid=$('#product-grid');const query=state.search.trim().toLocaleLowerCase('pt-BR');const shown=products.filter(product=>(state.category==='Tudo'||product.category===state.category)&&(!query||`${product.name} ${product.description} ${product.category}`.toLocaleLowerCase('pt-BR').includes(query)));
  grid.innerHTML=shown.length?shown.map(product=>{const stock=stockFor(product);const enabled=available(product);const quantity=state.cart[product.id]||0;const tag=product.seasonal?`<span class="product-tag seasonal-tag">${product.tag}</span>`:product.tag?`<span class="product-tag">${product.tag}</span>`:'';return `<article class="product-card"><div class="product-art"><img class="product-photo" src="${product.image}" alt="${product.name}" loading="lazy" decoding="async">${tag}${!enabled?`<span class="product-unavailable">${product.seasonal?'Disponível no período junino':'Indisponível nesta unidade'}</span>`:''}</div><div class="product-info"><span class="product-category">${product.category}</span><h3>${product.name}</h3><p class="product-description">${product.description}</p><div class="product-bottom"><span class="product-price">${money(product.price)}</span><button class="add-button" type="button" data-add="${product.id}" ${!enabled||quantity>=stock?'disabled':''}>${quantity?'+'+(quantity):'Adicionar'}</button></div></div></article>`}).join(''):`<div class="no-results"><strong>Nenhum item por aqui.</strong><p>Tente outra busca ou categoria.</p></div>`;
  $('#selected-unit-name').textContent=units[state.unit].name;
}
function cartData(){return Object.entries(state.cart).map(([id,quantity])=>({product:productById(id),quantity})).filter(item=>item.product)}
function cartSubtotal(){return cartData().reduce((sum,item)=>sum+item.quantity*item.product.price,0)}
function cartDiscount(){return state.rewardApplied?Math.min(500,cartSubtotal()):0}
function renderLoyalty(){$('#loyalty-points-value').textContent=state.points;$('#rewards-balance').textContent=state.points;$('#reward-redeem').disabled=state.points<100;$('#reward-redeem').textContent=state.rewardApplied?'Remover':'Resgatar';$('#loyalty-progress-value').style.width=`${Math.min(state.points/500*100,100)}%`}
function renderCart(){const lines=$('#cart-lines'),items=cartData(),count=items.reduce((sum,item)=>sum+item.quantity,0),subtotal=cartSubtotal(),discount=cartDiscount(),total=subtotal-discount;$('#cart-count').textContent=count;$('#cart-footer').hidden=!count;if(!count){lines.innerHTML='<div class="empty-cart"><span aria-hidden="true">☼</span><strong>Tem espaço pra coisa boa.</strong><p>Adicione algo do cardápio para começar.</p></div>'}else{lines.innerHTML=items.map(({product,quantity})=>{const isAvailable=quantity<=stockFor(product)&&available(product);return `<div class="cart-line"><div><strong>${product.name}</strong><small>${money(product.price)} cada</small><div class="qty-control"><button type="button" aria-label="Remover uma unidade de ${product.name}" data-qty="${product.id}" data-delta="-1">−</button><span>${quantity}</span><button type="button" aria-label="Adicionar uma unidade de ${product.name}" data-qty="${product.id}" data-delta="1" ${quantity>=stockFor(product)||!available(product)?'disabled':''}>+</button></div>${!isAvailable?'<div class="cart-unavailable">Indisponível na unidade atual</div>':''}</div><span class="line-total">${money(product.price*quantity)}</span></div>`}).join('')};$('#cart-subtotal').textContent=money(total);$('#cart-discount-row').hidden=!discount;$('#mobile-cart-count').textContent=`${count} ${count===1?'item':'itens'}`;$('#mobile-cart-total').textContent=money(total);$('#mobile-cart-bar').hidden=!count;$('#checkout-open').disabled=items.some(({product,quantity})=>!available(product)||quantity>stockFor(product));$('#mobile-checkout').disabled=$('#checkout-open').disabled;renderProducts();renderLoyalty()}
function renderUnit(){const unit=units[state.unit];$('#unit-description').textContent=unit.description;$('#selected-unit-name').textContent=unit.name;$('#checkout-unit').textContent=unit.name}
function renderCheckout(){const items=cartData(),subtotal=cartSubtotal(),discount=cartDiscount(),total=subtotal-discount;let rows=items.map(({product,quantity})=>`<div class="summary-line"><span>${quantity} × ${product.name}</span><strong>${money(quantity*product.price)}</strong></div>`).join('');if(discount)rows+=`<div class="summary-line checkout-reward"><span>Raízes Club · resgate</span><strong>- ${money(discount)}</strong></div>`;$('#checkout-lines').innerHTML=rows||'<p class="demo-label">Sua sacola está vazia.</p>';$('#checkout-total').textContent=money(total);$('#checkout-unit').textContent=units[state.unit].name}
function openCheckout(){if(!cartData().length)return showToast('Adicione ao menos um item para continuar.');if(cartData().some(({product,quantity})=>!available(product)||quantity>stockFor(product)))return showToast('Revise a sacola: há itens indisponíveis nesta unidade.');renderCheckout();$('#payment-state').hidden=true;$('#checkout-form').hidden=false;$('#checkout-form').reset();$('#submit-order-label').textContent='Enviar pedido para pagamento';setDialog('checkout-dialog')}
function orderSteps(status){const all=['Pedido confirmado','Em preparo','Pronto para retirada'];const order=['confirmed','preparing','ready'].indexOf(status);return all.map((label,index)=>`<div class="timeline-step ${index<=order?'done':''} ${index===order?'current':''}">${label}</div>`).join('')}
function showOrder(success=true,message=''){const order=state.order;if(!order)return;$('#order-state-icon').classList.toggle('error',!success);$('#order-state-icon').textContent=success?'✓':'!';$('#order-kicker').textContent=success?'PAGAMENTO CONFIRMADO':'PAGAMENTO NÃO CONCLUÍDO';$('#order-title').innerHTML=success?'Pedido recebido <em>com carinho.</em>':'Não foi dessa vez <em>com o pagamento.</em>';
  $('#order-message').textContent=message||(success?'Seu pedido está confirmado. A cozinha já vai preparar tudo fresquinho.':'Revise a forma de pagamento ou tente novamente. Sua sacola continua salva nesta sessão.');$('#order-code').textContent=order.code;$('#order-unit').textContent=units[order.unit].name;$('#order-timeline').innerHTML=success?orderSteps(order.status):'';$('#advance-status').hidden=!success||order.status==='ready';$('#advance-status').textContent=order.status==='confirmed'?'Simular: em preparo':'Simular: pronto para retirada';setDialog('order-dialog')}
function processPayment(event){event.preventDefault();const form=event.currentTarget;const name=$('#customer-name').value.trim();const phone=$('#customer-phone').value.replace(/\D/g,'');if(name.length<2){$('#customer-name').setCustomValidity('Informe seu nome com pelo menos 2 caracteres.');$('#customer-name').reportValidity();$('#customer-name').setCustomValidity('');return}if(phone.length<10||phone.length>13){$('#customer-phone').setCustomValidity('Informe um celular com DDD.');$('#customer-phone').reportValidity();$('#customer-phone').setCustomValidity('');return}
  const stateBox=$('#payment-state');stateBox.hidden=false;stateBox.className='payment-state pending';stateBox.textContent='Enviando solicitação ao parceiro de pagamento…';$('#submit-order-label').textContent='Aguardando confirmação…';form.querySelector('button[type="submit"]').disabled=true;
  const simulation=$('#payment-result').value;setTimeout(()=>{form.querySelector('button[type="submit"]').disabled=false;if(simulation==='declined'){stateBox.className='payment-state error';stateBox.textContent='O parceiro recusou o pagamento. Nenhuma cobrança foi realizada. Confira o método de pagamento e tente novamente.';$('#submit-order-label').textContent='Tentar novamente';return}if(simulation==='offline'){stateBox.className='payment-state error';stateBox.textContent='Não foi possível obter resposta do parceiro agora. O pedido não foi confirmado. Sua sacola continua disponível; tente novamente em instantes.';$('#submit-order-label').textContent='Tentar novamente';return}
    const items=cartData(),subtotal=cartSubtotal(),discount=cartDiscount(),total=subtotal-discount;state.order={code:`RN-${String(Math.floor(1000+Math.random()*9000))}`,unit:state.unit,items:items.map(({product,quantity})=>({id:product.id,quantity})),total,discount,status:'confirmed',createdAt:new Date().toISOString()};if(state.rewardApplied)state.points=Math.max(0,state.points-100);state.points+=Math.floor(total/100);state.rewardApplied=false;saveOrder();stateBox.hidden=true;closeDialog('checkout-dialog');state.cart={};renderCart();showOrder(true,'Retorno de aprovação simulado. Nenhuma unidade recebeu o pedido; o celular informado não foi armazenado.');if($('#marketing-consent').checked)showToast('Preferência de campanha limitada a esta sessão; nenhuma mensagem foi enviada.');
  },850)}
function addItem(id){const product=productById(id);if(!product||!available(product))return showToast('Este item não está disponível nesta unidade agora.');if((state.cart[id]||0)>=stockFor(product))return showToast('A disponibilidade máxima deste item foi atingida.');state.cart[id]=(state.cart[id]||0)+1;renderCart();showToast(`${product.name} adicionado à sacola.`)}
function changeQty(id,delta){const product=productById(id);if(!product)return;const next=(state.cart[id]||0)+delta;if(next<=0)delete state.cart[id];else if(next<=stockFor(product)&&available(product))state.cart[id]=next;else return showToast('Não há mais unidades disponíveis nesta unidade.');renderCart()}
function simulateAccount(event){event.preventDefault();const email=$('#account-email').value.trim();if(!email)return;const mode=$('input[name="account-mode"]:checked').value;closeDialog('account-dialog');showToast(mode==='register'?'Cadastro sem integração; seus dados não foram salvos.':'Acesso sem integração; nenhum e-mail foi enviado.')}
function advanceStatus(){if(!state.order)return;if(state.order.status==='confirmed')state.order.status='preparing';else if(state.order.status==='preparing')state.order.status='ready';saveOrder();showOrder(true,state.order.status==='ready'?'Seu pedido está pronto para retirada. Apresente o código no balcão.':'A cozinha começou a preparar seu pedido. Você receberá uma atualização quando estiver pronto.')}

$('#category-row').addEventListener('click',event=>{const button=event.target.closest('[data-category]');if(!button)return;state.category=button.dataset.category;renderCategories();renderProducts()});
$('#product-grid').addEventListener('click',event=>{const button=event.target.closest('[data-add]');if(button)addItem(button.dataset.add)});
$('#cart-lines').addEventListener('click',event=>{const button=event.target.closest('[data-qty]');if(button)changeQty(button.dataset.qty,Number(button.dataset.delta))});
$('#unit-select').addEventListener('change',event=>{state.unit=event.target.value;renderUnit();renderCart();showToast(`Cardápio atualizado: ${units[state.unit].name}.`)});
$('#channel-select').addEventListener('change',event=>{state.channel=event.target.value;const channel={web:'Web',app:'Aplicativo',totem:'Totem da loja'}[state.channel];showToast(`Canal selecionado: ${channel}.`)});
$('#menu-search').addEventListener('input',event=>{state.search=event.target.value;renderProducts()});
$('#account-open').addEventListener('click',()=>setDialog('account-dialog'));
$('#order-open').addEventListener('click',()=>{if(state.order)showOrder(true)});
$('#account-form').addEventListener('submit',simulateAccount);
$('#checkout-open').addEventListener('click',openCheckout);$('#mobile-checkout').addEventListener('click',openCheckout);
$('#checkout-form').addEventListener('submit',processPayment);
$('#advance-status').addEventListener('click',advanceStatus);
$('#close-order').addEventListener('click',()=>closeDialog('order-dialog'));
$('#privacy-open').addEventListener('click',()=>setDialog('privacy-dialog'));
$('#rewards-open').addEventListener('click',()=>setDialog('rewards-dialog'));
$('#campaign-details').addEventListener('click',()=>setDialog('campaign-dialog'));

document.addEventListener('click',event=>{if(event.target.closest('[data-open-privacy]')){document.querySelectorAll('dialog[open]').forEach(dialog=>dialog.close());setDialog('privacy-dialog')}const reward=event.target.closest('[data-reward]');if(reward&&!reward.disabled){state.rewardApplied=!state.rewardApplied;closeDialog('rewards-dialog');renderCart();showToast(state.rewardApplied?'Desconto de R$ 5,00 pré-selecionado; finalize o pedido para usá-lo.':'Desconto removido da sacola.')}});
renderCategories();renderUnit();renderProducts();renderCart();renderLoyalty();if(state.order)$('#order-open').hidden=false;
